language: android
dist: xenial
android:
  components:
    - build-tools-29.0.1
    - android-29
    
licenses:
  - 'android-sdk-license-.+'
    
before_install:
  - yes | sdkmanager "platforms;android-29"
